### PR TITLE
Adding basic test setup

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by jonparrott** [comment]
@andrewsg PTAL

**Comment by andrewsg** [comment]
LGTM

**Comment by jonparrott** [comment]
Thanks, going to wait for travis to complete.

What other tests do you think would be good to have? Running common frameworks and wsgi servers?

**Comment by jonparrott** [comment]
:cry: this test takes ages! I'll likely move this particular test to devrel-jenkins.

**Pull request merged**
