### PR TITLE
Adding tests for virtualenv usage

### PR DESCRIPTION
**Pull request by jonparrott**
Adding tests for virtualenv usage.

### CODE REVIEW

**Comment by andrewsg** [comment]
LGTM

**Comment by andrewsg** [comment]
Hmm, actually, I think I'd prefer if the user Dockerfile contained all three steps for virtualenv activation. There's less magic and less that can go wrong in the base image. But, I'll leave the final decision up to you.

**Comment by jonparrott** [comment]
I'm on the fence on this as well. Perhaps @JustinBeckwith can be the tie-breaker?

**Comment by JustinBeckwith** [comment]
For someone that wants that much control over their environment, I would image they're going to use their own Dockerfile with a more standard base image (not app engine).  I'd prefer to optimize for keeping user-generated dockerfiles small, and put as much logic in the base image as we can.  That having been said, you guys are the experts here :)

**Comment by andrewsg** [comment]
I feel like small isn't the most important goal. The Dockerfile that the user does NOT edit is mysterious; they have to look it up explicitly. So in order to reduce mystery (and the feeling that there's magic happening the user doesn't understand) I'd prefer to have it all in the user Dockerfile.

**Comment by JustinBeckwith** [comment]
My efforts to break the tie have been thwarted :)  If Jon's on the fence and you feel strongly, but all means put the setup in the user generated dockerfile. I'm really fine either way.

**Comment by jonparrott** [comment]
Andrew just changed my opinion. I'll update this PR shortly.

**Comment by jonparrott** [comment]
Updated the PR, now I'm just adding tests for the venvs.

**Pull request merged**
